### ISSUE TITLE
A new MapImageEngine?

### ISSUE THREAD

**Issue by GamerDaniel3000** [korado531m7/ImageConverter#1]
Is this a new version of MapImageEngine?

**Comment by korado531m7** [comment]
It is a plugin that can convert image into block.
Please see this

Before converting:
https://github.com/korado531m7/ImageConverter/blob/d02e39d72a96cf3d8a033adf6c0ecd486b959a11/Example/before.png

After Converted:
https://github.com/korado531m7/ImageConverter/blob/d02e39d72a96cf3d8a033adf6c0ecd486b959a11/Example/after.png
